const INIT_MENU_LIST = "QUERY_MENU_LIST"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const CHANGE_ADD_CONFIRM_LOADING = "CHANGE_ADD_CONFIRM_LOADING"
const CHANGE_EDIT_CONFIRM_LOADING = "CHANGE_EDIT_CONFIRM_LOADING"
const CHANGE_EDIT_MODAL_VISIBLE = "CHANGE_EDIT_MODAL_VISIBLE"
const CHANGE_EDIT_RECORD = "CHANGE_EDIT_RECORD"
const INIT_SLIDER_MENU_LIST = "INIT_SLIDER_MENU_LIST"


export {
  INIT_MENU_LIST,
  CHANGE_ADD_MODAL_VISIBLE,
  CHANGE_ADD_CONFIRM_LOADING,
  CHANGE_EDIT_CONFIRM_LOADING,
  CHANGE_EDIT_MODAL_VISIBLE,
  CHANGE_EDIT_RECORD,
  INIT_SLIDER_MENU_LIST,
}