const ORG_INIT_ORG_LIST = "ORG_INIT_ORG_LIST"
const ORG_SET_ORG_NAME = "ORG_SET_ORG_NAME"
const ORG_SET_ORG_CODE = "ORG_SET_ORG_CODE"
const ORG_SET_ORG_DESC = "ORG_SET_ORG_DESC"
const ORG_INIT_FORM_VALUES = "ORG_INIT_FORM_VALUES"
const ORG_INIT_ORG_TREE_DATA = "ORG_INIT_ORG_TREE_DATA"
const ORG_SET_EDIT_TREE_VALUE = "ORG_SET_EDIT_TREE_VALUE"
const ORG_CHANGE_SAVE_LOADING = "ORG_CHANGE_SAVE_LOADING"

export {
  ORG_INIT_ORG_LIST,
  ORG_SET_ORG_NAME,
  ORG_SET_ORG_CODE,
  ORG_SET_ORG_DESC,
  ORG_INIT_FORM_VALUES,
  ORG_INIT_ORG_TREE_DATA,
  ORG_SET_EDIT_TREE_VALUE,
  ORG_CHANGE_SAVE_LOADING,
}