const INIT_ORG_LIST = "INIT_ORG_LIST"
const SET_ORG_NAME = "SET_ORG_NAME"
const SET_ORG_CODE = "SET_ORG_CODE"
const SET_ORG_DESC = "SET_ORG_DESC"
const INIT_FORM_VALUES = "INIT_FORM_VALUES"
const INIT_ORG_TREE_DATA = "INIT_ORG_TREE_DATA"
const SET_EDIT_TREE_VALUE = "SET_EDIT_TREE_VALUE"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"

export {
  INIT_ORG_LIST,
  SET_ORG_NAME,
  SET_ORG_CODE,
  SET_ORG_DESC,
  INIT_FORM_VALUES,
  INIT_ORG_TREE_DATA,
  SET_EDIT_TREE_VALUE,
  CHANGE_SAVE_LOADING,
}