const QUERY_LIST = "QUERY_LIST"
const QUERY_PREFERENTTIAL_LIST = "QUERY_PREFERENTTIAL_LIST"
const QUERY_BILLING_LIST = "QUERY_BILLING_LIST"
const QUERY_PRODUCT_LIST = "QUERY_PRODUCT_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_MODAL_VISIBLE = "CHANGE_MODAL_VISIBLE"
const CHANGE_EDIT_STATUS = "CHANGE_EDIT_STATUS"
const CHANGE_CONFIG_STRATEGY_NAME = "CHANGE_CONFIG_STRATEGY_NAME"
const CHANGE_CONFIG_STRATEGY_CODE = "CHANGE_CONFIG_STRATEGY_CODE"
const CHANGE_CONFIG_BILLING_NAME = "CHANGE_CONFIG_BILLING_NAME"
const CHANGE_CONFIG_BILLING_CODE = "CHANGE_CONFIG_BILLING_CODE"
const CHANGE_CONFIG_PRODUCT_NAME = "CHANGE_CONFIG_PRODUCT_NAME"
const CHANGE_CONFIG_PRODUCT_CODE = "CHANGE_CONFIG_PRODUCT_CODE"
const CHANGE_PRODUCT_SELECTED_KEYS = "CHANGE_PRODUCT_SELECTED_KEYS"
const CHANGE_BILLING_SELECTED_KEYS = "CHANGE_BILLING_SELECTED_KEYS"
const CHANGE_PREFERENTIAL_SELECTED_KEYS = "CHANGE_PREFERENTIAL_SELECTED_KEYS"
const CHANGE_RECORD = "CHANGE_RECORD"

export {
  QUERY_LIST,
  QUERY_PREFERENTTIAL_LIST,
  QUERY_BILLING_LIST,
  QUERY_PRODUCT_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_MODAL_VISIBLE,
  CHANGE_EDIT_STATUS,
  CHANGE_CONFIG_STRATEGY_NAME,
  CHANGE_CONFIG_STRATEGY_CODE,
  CHANGE_CONFIG_BILLING_NAME,
  CHANGE_CONFIG_BILLING_CODE,
  CHANGE_CONFIG_PRODUCT_NAME,
  CHANGE_CONFIG_PRODUCT_CODE,
  CHANGE_PRODUCT_SELECTED_KEYS,
  CHANGE_BILLING_SELECTED_KEYS,
  CHANGE_PREFERENTIAL_SELECTED_KEYS,
  CHANGE_RECORD
}