const QUERY_LIST = "QUERY_LIST";
const SAVE_LOADING = "SAVE_LOADING";
const SET_PARAM_NAME = "SET_PARAM_NAME";
const SET_PARAM_TYPE = "SET_PARAM_TYPE";
const SET_IS_NESS = "SET_IS_NESS";
const SET_PARAM_REMARKS = "SET_PARAM_REMARKS";

export {
  QUERY_LIST,
  SAVE_LOADING,
  SET_PARAM_NAME,
  SET_PARAM_TYPE,
  SET_IS_NESS,
  SET_PARAM_REMARKS
};
