const OAPI_PARAMS_QUERY_LIST = "OAPI_PARAMS_QUERY_LIST";
const OAPI_PARAMS_SAVE_LOADING = "OAPI_PARAMS_SAVE_LOADING";
const OAPI_PARAMS_SET_PARAM_NAME = "OAPI_PARAMS_SET_PARAM_NAME";
const OAPI_PARAMS_SET_PARAM_TYPE = "OAPI_PARAMS_SET_PARAM_TYPE";
const OAPI_PARAMS_SET_IS_NESS = "OAPI_PARAMS_SET_IS_NESS";
const OAPI_PARAMS_SET_PARAM_REMARKS = "OAPI_PARAMS_SET_PARAM_REMARKS";

export {
  OAPI_PARAMS_QUERY_LIST,
  OAPI_PARAMS_SAVE_LOADING,
  OAPI_PARAMS_SET_PARAM_NAME,
  OAPI_PARAMS_SET_PARAM_TYPE,
  OAPI_PARAMS_SET_IS_NESS,
  OAPI_PARAMS_SET_PARAM_REMARKS
};
