const SAFE_STRATEGY_QUERY_LIST = "SAFE_STRATEGY_QUERY_LIST"
const SAFE_STRATEGY_CHANGE_MODAL_VISIBLE = "SAFE_STRATEGY_CHANGE_MODAL_VISIBLE"
const SAFE_STRATEGY_SAVE_LOADING = "SAFE_STRATEGY_SAVE_LOADING"
const SAFE_STRATEGY_CHANGE_STRATEGY_NAME = "SAFE_STRATEGY_CHANGE_STRATEGY_NAME"
const SAFE_STRATEGY_CHANGE_STRATEGY_CODE = "SAFE_STRATEGY_CHANGE_STRATEGY_CODE"
const SAFE_STRATEGY_CHANGE_STRATEGY_STATUS = "SAFE_STRATEGY_CHANGE_STRATEGY_STATUS"
const SAFE_STRATEGY_CHANGE_CONFIRM_LOADING = "SAFE_STRATEGY_CHANGE_CONFIRM_LOADING"

export {
  SAFE_STRATEGY_QUERY_LIST,
  SAFE_STRATEGY_CHANGE_MODAL_VISIBLE,
  SAFE_STRATEGY_SAVE_LOADING,
  SAFE_STRATEGY_CHANGE_STRATEGY_NAME,
  SAFE_STRATEGY_CHANGE_STRATEGY_CODE,
  SAFE_STRATEGY_CHANGE_STRATEGY_STATUS,
  SAFE_STRATEGY_CHANGE_CONFIRM_LOADING
}