const QUERY_LIST = "QUERY_LIST"
const CHANGE_MODAL_VISIBLE = "CHANGE_MODAL_VISIBLE"
const SAVE_LOADING = "SAVE_LOADING"
const CHANGE_STRATEGY_NAME = "CHANGE_STRATEGY_NAME"
const CHANGE_STRATEGY_CODE = "CHANGE_STRATEGY_CODE"
const CHANGE_STRATEGY_STATUS = "CHANGE_STRATEGY_STATUS"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"

export {
  QUERY_LIST,
  CHANGE_MODAL_VISIBLE,
  SAVE_LOADING,
  CHANGE_STRATEGY_NAME,
  CHANGE_STRATEGY_CODE,
  CHANGE_STRATEGY_STATUS,
  CHANGE_CONFIRM_LOADING
}