const ACCOUNT_STATISTICAL_TYPES_LIST = "ACCOUNT_STATISTICAL_TYPES_LIST"
const ACCOUNT_STATISTICAL_TABLE_LIST = "ACCOUNT_STATISTICAL_TABLE_LIST"

const ACCOUNT_STATISTICAL_CHANGE_SEARCH_PARAMS = "ACCOUNT_STATISTICAL_CHANGE_SEARCH_PARAMS"

export {
  ACCOUNT_STATISTICAL_TYPES_LIST,
  ACCOUNT_STATISTICAL_TABLE_LIST,
  ACCOUNT_STATISTICAL_CHANGE_SEARCH_PARAMS,
}