const QUESTION_QUERY_LIST = "QUESTION_QUERY_LIST"
const QUESTION_CHANGE_SEARCH_PARAMS = "QUESTION_CHANGE_SEARCH_PARAMS"
const QUESTION_CHANGE_EDIT_TITLE = "QUESTION_CHANGE_EDIT_TITLE"
const QUESTION_CHANGE_EDIT_TYPE = "QUESTION_CHANGE_EDIT_TYPE"
const QUESTION_CHANGE_EDIT_CONTENT = "QUESTION_CHANGE_EDIT_CONTENT"
const QUESTION_CHANGE_EDIT_REFTITLE = "QUESTION_CHANGE_EDIT_REFTITLE"
const QUESTION_INIT_NOTICE_DETAIL = "QUESTION_INIT_NOTICE_DETAIL"
const QUESTION_CHANGE_EDIT_STATE = "QUESTION_CHANGE_EDIT_STATE"

export {
  QUESTION_QUERY_LIST,
  QUESTION_CHANGE_SEARCH_PARAMS,
  QUESTION_CHANGE_EDIT_TITLE,
  QUESTION_CHANGE_EDIT_TYPE,
  QUESTION_CHANGE_EDIT_CONTENT,
  QUESTION_CHANGE_EDIT_REFTITLE,
  QUESTION_INIT_NOTICE_DETAIL,
  QUESTION_CHANGE_EDIT_STATE,
}