const PREFERENTIAL_QUERY_LIST = "PREFERENTIAL_QUERY_LIST"
const PREFERENTIAL_CHANGE_SEARCH_PARAMS = "PREFERENTIAL_CHANGE_SEARCH_PARAMS"
const PREFERENTIAL_CHANGE_EDIT_STRATEGY_NAME = "PREFERENTIAL_CHANGE_EDIT_STRATEGY_NAME"
const PREFERENTIAL_CHANGE_EDIT_STRATEGY_DESC = "PREFERENTIAL_CHANGE_EDIT_STRATEGY_DESC"
const PREFERENTIAL_CHANGE_SAVE_LOADING = "PREFERENTIAL_CHANGE_SAVE_LOADING"
const PREFERENTIAL_CHANGE_EDIT_TYPE = "PREFERENTIAL_CHANGE_EDIT_TYPE"
const PREFERENTIAL_CHANGE_EDIT_STRATEGY_RULE = "PREFERENTIAL_CHANGE_EDIT_STRATEGY_RULE"

export {
  PREFERENTIAL_QUERY_LIST,
  PREFERENTIAL_CHANGE_SEARCH_PARAMS,
  PREFERENTIAL_CHANGE_EDIT_STRATEGY_NAME,
  PREFERENTIAL_CHANGE_EDIT_STRATEGY_DESC,
  PREFERENTIAL_CHANGE_SAVE_LOADING,
  PREFERENTIAL_CHANGE_EDIT_TYPE,
  PREFERENTIAL_CHANGE_EDIT_STRATEGY_RULE,
}