const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_STRATEGY_NAME = "CHANGE_EDIT_STRATEGY_NAME"
const CHANGE_EDIT_STRATEGY_DESC = "CHANGE_EDIT_STRATEGY_DESC"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"
const CHANGE_EDIT_TYPE = "CHANGE_EDIT_TYPE"
const CHANGE_EDIT_STRATEGY_RULE = "CHANGE_EDIT_STRATEGY_RULE"

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_STRATEGY_NAME,
  CHANGE_EDIT_STRATEGY_DESC,
  CHANGE_SAVE_LOADING,
  CHANGE_EDIT_TYPE,
  CHANGE_EDIT_STRATEGY_RULE,
}