const QUERY_NOTICE_LIST = "QUERY_NOTICE_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_TITLE = "CHANGE_EDIT_TITLE"
const CHANGE_EDIT_CONTENT = "CHANGE_EDIT_CONTENT"
const CHANGE_EDIT_REFTITLE = "CHANGE_EDIT_REFTITLE"

export {
  QUERY_NOTICE_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_TITLE,
  CHANGE_EDIT_CONTENT,
  CHANGE_EDIT_REFTITLE,
}