const NOTICE_QUERY_NOTICE_LIST = "NOTICE_QUERY_NOTICE_LIST"
const NOTICE_CHANGE_SEARCH_PARAMS = "NOTICE_CHANGE_SEARCH_PARAMS"
const NOTICE_CHANGE_EDIT_TITLE = "NOTICE_CHANGE_EDIT_TITLE"
const NOTICE_CHANGE_EDIT_CONTENT = "NOTICE_CHANGE_EDIT_CONTENT"
const NOTICE_CHANGE_EDIT_REFTITLE = "NOTICE_CHANGE_EDIT_REFTITLE"
const NOTICE_INIT_NOTICE_DETAIL = "NOTICE_INIT_NOTICE_DETAIL"
const NOTICE_CHANGE_EDIT_STATE = "NOTICE_CHANGE_EDIT_STATE"
const NOTICE_CHANGE_EDIT_NOTICE_TYPE = "NOTICE_CHANGE_EDIT_NOTICE_TYPE"

export {
  NOTICE_QUERY_NOTICE_LIST,
  NOTICE_CHANGE_SEARCH_PARAMS,
  NOTICE_CHANGE_EDIT_TITLE,
  NOTICE_CHANGE_EDIT_CONTENT,
  NOTICE_CHANGE_EDIT_REFTITLE,
  NOTICE_INIT_NOTICE_DETAIL,
  NOTICE_CHANGE_EDIT_STATE,
  NOTICE_CHANGE_EDIT_NOTICE_TYPE,
}