const QUERY_USER_LIST = "QUERY_USER_LIST"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"

export { QUERY_USER_LIST, CHANGE_ADD_MODAL_VISIBLE, CHANGE_SEARCH_PARAMS }