const DICT_DATA_QUERY_DICT_TYPE_LIST = "DICT_DATA_QUERY_DICT_TYPE_LIST"
const DICT_DATA_CHANGE_SEARCH_PARAMS = "DICT_DATA_CHANGE_SEARCH_PARAMS"
const DICT_DATA_CHANGE_CONFIRM_LOADING = "DICT_DATA_CHANGE_CONFIRM_LOADING"
const DICT_DATA_CHANGE_ADD_MODAL_VISIBLE = "DICT_DATA_CHANGE_ADD_MODAL_VISIBLE"
const DICT_DATA_QUERY_DICT_DATA_LIST = "DICT_DATA_QUERY_DICT_DATA_LIST"

export {
  DICT_DATA_CHANGE_CONFIRM_LOADING,
  DICT_DATA_QUERY_DICT_TYPE_LIST,
  DICT_DATA_CHANGE_ADD_MODAL_VISIBLE,
  DICT_DATA_QUERY_DICT_DATA_LIST,
  DICT_DATA_CHANGE_SEARCH_PARAMS
}