const APPLY_ORDER_QUERY_LIST = "APPLY_ORDER_QUERY_LIST";
const APPLY_ORDER_CHANGE_SEARCH_PARAMS = "APPLY_ORDER_CHANGE_SEARCH_PARAMS";
const APPLY_ORDER_CHANGE_SAVE_LOADING = "APPLY_ORDER_CHANGE_SAVE_LOADING";
const APPLY_ORDER_INIT_DETAIL = "APPLY_ORDER_INIT_DETAIL";
const APPLY_ORDER_INIT_ALL_APP_TYPES = "APPLY_ORDER_INIT_ALL_APP_TYPES";
const APPLY_ORDER_INIT_ALL_LANDING_MODES = "APPLY_ORDER_INIT_ALL_LANDING_MODES";
const APPLY_ORDER_INIT_ALL_SUPPORT_CAS = "APPLY_ORDER_INIT_ALL_SUPPORT_CAS";
const APPLY_ORDER_INIT_GET_FILE_LIST = "APPLY_ORDER_INIT_GET_FILE_LIST";
const APPLY_ORDER_CHANGE_CONFIRM_VISIBLE = "APPLY_ORDER_CHANGE_CONFIRM_VISIBLE";
const APPLY_ORDER_CHANGE_CONFIRM_LOADING = "APPLY_ORDER_CHANGE_CONFIRM_LOADING";
const APPLY_ORDER_INIT_CATALOG = "APPLY_ORDER_INIT_CATALOG";
const APPLY_ORDER_INIT_PRODUCT_LIST = "APPLY_ORDER_INIT_PRODUCT_LIST";

export {
  APPLY_ORDER_QUERY_LIST,
  APPLY_ORDER_CHANGE_SEARCH_PARAMS,
  APPLY_ORDER_CHANGE_SAVE_LOADING,
  APPLY_ORDER_INIT_DETAIL,
  APPLY_ORDER_INIT_ALL_LANDING_MODES,
  APPLY_ORDER_INIT_ALL_APP_TYPES,
  APPLY_ORDER_INIT_ALL_SUPPORT_CAS,
  APPLY_ORDER_INIT_GET_FILE_LIST,
  APPLY_ORDER_CHANGE_CONFIRM_VISIBLE,
  APPLY_ORDER_CHANGE_CONFIRM_LOADING,
  APPLY_ORDER_INIT_CATALOG,
  APPLY_ORDER_INIT_PRODUCT_LIST
};
