const QUERY_LIST = "QUERY_LIST";
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS";
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING";
const INIT_DETAIL = "INIT_DETAIL";
const INIT_ALL_APP_TYPES = "INIT_ALL_APP_TYPES";
const INIT_ALL_LANDING_MODES = "INIT_ALL_LANDING_MODES";
const INIT_ALL_SUPPORT_CAS = "INIT_ALL_SUPPORT_CAS";
const INIT_GET_FILE_LIST = "INIT_GET_FILE_LIST";
const CHANGE_CONFIRM_VISIBLE = "CHANGE_CONFIRM_VISIBLE";
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING";
const INIT_CATALOG = "INIT_CATALOG";
const INIT_PRODUCT_LIST = "INIT_PRODUCT_LIST";

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_SAVE_LOADING,
  INIT_DETAIL,
  INIT_ALL_LANDING_MODES,
  INIT_ALL_APP_TYPES,
  INIT_ALL_SUPPORT_CAS,
  INIT_GET_FILE_LIST,
  CHANGE_CONFIRM_VISIBLE,
  CHANGE_CONFIRM_LOADING,
  INIT_CATALOG,
  INIT_PRODUCT_LIST
};
