const INIT_MENU_LIST = "QUERY_MENU_LIST"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const CHANGE_ADD_CONFIRM_LOADING = "CHANGE_ADD_CONFIRM_LOADING"
const CHANGE_EDIT_CONFIRM_LOADING = "CHANGE_EDIT_CONFIRM_LOADING"
const CHANGE_EDIT_MODAL_VISIBLE = "CHANGE_EDIT_MODAL_VISIBLE"


export {
  INIT_MENU_LIST,
  CHANGE_ADD_MODAL_VISIBLE,
  CHANGE_ADD_CONFIRM_LOADING,
  CHANGE_EDIT_CONFIRM_LOADING,
  CHANGE_EDIT_MODAL_VISIBLE,
}