const MENU_INIT_MENU_LIST = "MENU_QUERY_MENU_LIST"
const MENU_CHANGE_ADD_MODAL_VISIBLE = "MENU_CHANGE_ADD_MODAL_VISIBLE"
const MENU_CHANGE_ADD_CONFIRM_LOADING = "MENU_CHANGE_ADD_CONFIRM_LOADING"
const MENU_CHANGE_EDIT_CONFIRM_LOADING = "MENU_CHANGE_EDIT_CONFIRM_LOADING"
const MENU_CHANGE_EDIT_MODAL_VISIBLE = "MENU_CHANGE_EDIT_MODAL_VISIBLE"
const MENU_CHANGE_EDIT_RECORD = "MENU_CHANGE_EDIT_RECORD"
const MENU_INIT_SLIDER_MENU_LIST = "MENU_INIT_SLIDER_MENU_LIST"


export {
  MENU_INIT_MENU_LIST,
  MENU_CHANGE_ADD_MODAL_VISIBLE,
  MENU_CHANGE_ADD_CONFIRM_LOADING,
  MENU_CHANGE_EDIT_CONFIRM_LOADING,
  MENU_CHANGE_EDIT_MODAL_VISIBLE,
  MENU_CHANGE_EDIT_RECORD,
  MENU_INIT_SLIDER_MENU_LIST,
}