const INIT_APP_STATISTICAL_TYPES_LIST = "INIT_APP_STATISTICAL_TYPES_LIST"
const INIT_APP_STATISTICAL_TABLE_LIST = "INIT_APP_STATISTICAL_TABLE_LIST"

const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"

export {
  INIT_APP_STATISTICAL_TYPES_LIST,
  INIT_APP_STATISTICAL_TABLE_LIST,
  CHANGE_SEARCH_PARAMS,
}