const QUERY_DICT_TYPE_LIST = "QUERY_DICT_TYPE_LIST";
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS";
const QUERY_DICT_DATA_LIST = "QUERY_DICT_DATA_LIST";
const INIT_ALL_PRODUCT_TYPE = "INIT_ALL_PRODUCT_TYPE";
const SET_PRODUCT_NAME = "SET_PRODUCT_NAME";
const SET_EDIT_CONTENT = "SET_EDIT_CONTENT";
const SET_PRODUCT_PRICE = "SET_PRODUCT_PRICE";
const SET_PRODUCT_PAYING = "SET_PRODUCT_PAYING";
const SET_PRODUCT_TYPE_CODE = "SET_PRODUCT_TYPE_CODE";
const SET_PRODUCT_REMARK = "SET_PRODUCT_REMARK";
const SET_PRODUCT_TAG = "SET_PRODUCT_TAG";

export {
  QUERY_DICT_TYPE_LIST,
  QUERY_DICT_DATA_LIST,
  INIT_ALL_PRODUCT_TYPE,
  CHANGE_SEARCH_PARAMS,
  SET_PRODUCT_NAME,
  SET_EDIT_CONTENT,
  SET_PRODUCT_PRICE,
  SET_PRODUCT_PAYING,
  SET_PRODUCT_TYPE_CODE,
  SET_PRODUCT_REMARK,
  SET_PRODUCT_TAG
};
