const QUERY_DICT_TYPE_LIST = "QUERY_DICT_TYPE_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const QUERY_DICT_DATA_LIST = "QUERY_DICT_DATA_LIST"
const INIT_ALL_PRODUCT_TYPE = "INIT_ALL_PRODUCT_TYPE"

export {
  CHANGE_CONFIRM_LOADING,
  QUERY_DICT_TYPE_LIST,
  CHANGE_ADD_MODAL_VISIBLE,
  QUERY_DICT_DATA_LIST,
  INIT_ALL_PRODUCT_TYPE,
  CHANGE_SEARCH_PARAMS
}