const PRODUCT_QUERY_DICT_TYPE_LIST = "PRODUCT_QUERY_DICT_TYPE_LIST";
const PRODUCT_CHANGE_SEARCH_PARAMS = "PRODUCT_CHANGE_SEARCH_PARAMS";
const PRODUCT_QUERY_DICT_DATA_LIST = "PRODUCT_QUERY_DICT_DATA_LIST";
const PRODUCT_INIT_ALL_PRODUCT_TYPE = "PRODUCT_INIT_ALL_PRODUCT_TYPE";
const PRODUCT_SET_PRODUCT_NAME = "PRODUCT_SET_PRODUCT_NAME";
const PRODUCT_SET_EDIT_CONTENT = "PRODUCT_SET_EDIT_CONTENT";
const PRODUCT_SET_PRODUCT_PRICE = "PRODUCT_SET_PRODUCT_PRICE";
const PRODUCT_SET_PRODUCT_PAYING = "PRODUCT_SET_PRODUCT_PAYING";
const PRODUCT_SET_PRODUCT_TYPE_CODE = "PRODUCT_SET_PRODUCT_TYPE_CODE";
const PRODUCT_SET_PRODUCT_REMARK = "PRODUCT_SET_PRODUCT_REMARK";
const PRODUCT_SET_PRODUCT_TAG = "PRODUCT_SET_PRODUCT_TAG";
const PRODUCT_INIT_VERIFY_API_LIST = "PRODUCT_INIT_VERIFY_API_LIST";
const PRODUCT_SET_API_NAME = "PRODUCT_SET_API_NAME";
const PRODUCT_SET_ORDER_WORD = "PRODUCT_SET_ORDER_WORD";
const PRODUCT_CHANGE_SAVE_LOADING = "PRODUCT_CHANGE_SAVE_LOADING";

export {
  PRODUCT_QUERY_DICT_TYPE_LIST,
  PRODUCT_QUERY_DICT_DATA_LIST,
  PRODUCT_INIT_ALL_PRODUCT_TYPE,
  PRODUCT_CHANGE_SEARCH_PARAMS,
  PRODUCT_SET_PRODUCT_NAME,
  PRODUCT_SET_EDIT_CONTENT,
  PRODUCT_SET_PRODUCT_PRICE,
  PRODUCT_SET_PRODUCT_PAYING,
  PRODUCT_SET_PRODUCT_TYPE_CODE,
  PRODUCT_SET_PRODUCT_REMARK,
  PRODUCT_SET_PRODUCT_TAG,
  PRODUCT_INIT_VERIFY_API_LIST,
  PRODUCT_SET_API_NAME,
  PRODUCT_SET_ORDER_WORD,
  PRODUCT_CHANGE_SAVE_LOADING
};
