const CERTFICATION_INIT_LIST = "CERTFICATION_INIT_LIST"
const CERTFICATION_CHANGE_SEARCH_PARAMS = "CERTFICATION_CHANGE_SEARCH_PARAMS"
const CERTFICATION_CHANGE_EDIT_AUTH_NAME = "CERTFICATION_CHANGE_EDIT_AUTH_NAME"
const CERTFICATION_CHANGE_EDIT_URL = "CERTFICATION_CHANGE_EDIT_URL"
const CERTFICATION_CHANGE_AUTH_LEVE = "CERTFICATION_CHANGE_AUTH_LEVE"
const CERTFICATION_CHANGE_AUTH_STYLE = "CERTFICATION_CHANGE_AUTH_STYLE"
const CERTFICATION_CHANGE_EDIT_STATUS = "CERTFICATION_CHANGE_EDIT_STATUS"
const CERTFICATION_CLEAN_FORM = "CERTFICATION_CLEAN_FORM"
const CERTFICATION_CHANGE_EDIT_CONTENT = "CERTFICATION_CHANGE_EDIT_CONTENT"
const CERTFICATION_CHANGE_EDIT_REFTITLE = "CERTFICATION_CHANGE_EDIT_REFTITLE"
const CERTFICATION_INIT_NOTICE_DETAIL = "CERTFICATION_INIT_NOTICE_DETAIL"

export {
  CERTFICATION_INIT_LIST,
  CERTFICATION_CHANGE_SEARCH_PARAMS,
  CERTFICATION_CHANGE_EDIT_AUTH_NAME,
  CERTFICATION_CHANGE_EDIT_URL,
  CERTFICATION_CHANGE_AUTH_LEVE,
  CERTFICATION_CHANGE_AUTH_STYLE,
  CERTFICATION_CHANGE_EDIT_STATUS,
  CERTFICATION_CLEAN_FORM,
  CERTFICATION_CHANGE_EDIT_CONTENT,
  CERTFICATION_CHANGE_EDIT_REFTITLE,
  CERTFICATION_INIT_NOTICE_DETAIL,
}