const INIT_LIST = "QUERY_NOTICE_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_TITLE = "CHANGE_EDIT_TITLE"
const CHANGE_EDIT_CONTENT = "CHANGE_EDIT_CONTENT"
const CHANGE_EDIT_REFTITLE = "CHANGE_EDIT_REFTITLE"
const INIT_NOTICE_DETAIL = "INIT_NOTICE_DETAIL"


export {
  INIT_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_TITLE,
  CHANGE_EDIT_CONTENT,
  CHANGE_EDIT_REFTITLE,
  INIT_NOTICE_DETAIL,
}