const ROLE_QUERY_ROLE_LIST = "ROLE_QUERY_ROLE_LIST"
const ROLE_CHANGE_ADD_MODAL_VISIBLE = "ROLE_CHANGE_ADD_MODAL_VISIBLE"
const ROLE_CHANGE_MENU_MODAL_VISIBLE = "ROLE_CHANGE_MENU_MODAL_VISIBLE"
const ROLE_INIT_MENU_LIST = "ROLE_INIT_MENU_LIST"
const ROLE_CHANGE_CHECKED_KEYS_ACTION = "ROLE_CHANGE_CHECKED_KEYS_ACTION"
const ROLE_CHANGE_CONFIRM_LOADING = "ROLE_CHANGE_CONFIRM_LOADING"

export {
  ROLE_QUERY_ROLE_LIST,
  ROLE_CHANGE_ADD_MODAL_VISIBLE,
  ROLE_CHANGE_MENU_MODAL_VISIBLE,
  ROLE_INIT_MENU_LIST,
  ROLE_CHANGE_CHECKED_KEYS_ACTION,
  ROLE_CHANGE_CONFIRM_LOADING,
}