const QUERY_ROLE_LIST = "QUERY_ROLE_LIST"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_MENU_MODAL_VISIBLE = "CHANGE_MENU_MODAL_VISIBLE"
const INIT_MENU_LIST = "INIT_MENU_LIST"
const CHANGE_CHECKED_KEYS_ACTION = "CHANGE_CHECKED_KEYS_ACTION"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"

export {
  QUERY_ROLE_LIST,
  CHANGE_ADD_MODAL_VISIBLE,
  CHANGE_SEARCH_PARAMS,
  CHANGE_MENU_MODAL_VISIBLE,
  INIT_MENU_LIST,
  CHANGE_CHECKED_KEYS_ACTION,
  CHANGE_CONFIRM_LOADING,
}