const TOKEN_POWER_QUERY_LIST = "TOKEN_POWER_QUERY_LIST"
const TOKEN_POWER_CHANGE_SEARCH_PARAMS = "TOKEN_POWER_CHANGE_SEARCH_PARAMS"
const TOKEN_POWER_CHANGE_EDIT_TITLE = "TOKEN_POWER_CHANGE_EDIT_TITLE"
const TOKEN_POWER_CHANGE_EDIT_URL = "TOKEN_POWER_CHANGE_EDIT_URL"
const TOKEN_POWER_CHANGE_EDIT_REMARKS = "TOKEN_POWER_CHANGE_EDIT_REMARKS"
const TOKEN_POWER_CHANGE_SELECTED_ROW_KEYS = "TOKEN_POWER_CHANGE_SELECTED_ROW_KEYS"
const TOKEN_POWER_INIT_ROLE_ID = "TOKEN_POWER_INIT_ROLE_ID"
const TOKEN_POWER_CHANGE_SAVE_LOADING = "TOKEN_POWER_CHANGE_SAVE_LOADING"

export {
  TOKEN_POWER_QUERY_LIST,
  TOKEN_POWER_CHANGE_SEARCH_PARAMS,
  TOKEN_POWER_CHANGE_EDIT_TITLE,
  TOKEN_POWER_CHANGE_EDIT_URL,
  TOKEN_POWER_CHANGE_EDIT_REMARKS,
  TOKEN_POWER_CHANGE_SELECTED_ROW_KEYS,
  TOKEN_POWER_INIT_ROLE_ID,
  TOKEN_POWER_CHANGE_SAVE_LOADING,
}