const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_TITLE = "CHANGE_EDIT_TITLE"
const CHANGE_EDIT_URL = "CHANGE_EDIT_URL"
const CHANGE_EDIT_REMARKS = "CHANGE_EDIT_REMARKS"
const CHANGE_SELECTED_ROW_KEYS = "CHANGE_SELECTED_ROW_KEYS"
const INIT_ROLE_ID = "INIT_ROLE_ID"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_TITLE,
  CHANGE_EDIT_URL,
  CHANGE_EDIT_REMARKS,
  CHANGE_SELECTED_ROW_KEYS,
  INIT_ROLE_ID,
  CHANGE_SAVE_LOADING,
}