const FLAT_STATISTICAL_QUERY_LIST = "FLAT_STATISTICAL_QUERY_LIST"
const FLAT_STATISTICAL_CHANGE_SEARCH_PARAMS = "FLAT_STATISTICAL_CHANGE_SEARCH_PARAMS"

export {
  FLAT_STATISTICAL_QUERY_LIST,
  FLAT_STATISTICAL_CHANGE_SEARCH_PARAMS,
}