const QUERY_DICT_TYPE_LIST = "QUERY_DICT_TYPE_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"

export {
  CHANGE_CONFIRM_LOADING,
  QUERY_DICT_TYPE_LIST,
  CHANGE_ADD_MODAL_VISIBLE,

  CHANGE_SEARCH_PARAMS
}