const DICT_TYPE_QUERY_DICT_TYPE_LIST = "DICT_TYPE_QUERY_DICT_TYPE_LIST"
const DICT_TYPE_CHANGE_SEARCH_PARAMS = "DICT_TYPE_CHANGE_SEARCH_PARAMS"
const DICT_TYPE_CHANGE_CONFIRM_LOADING = "DICT_TYPE_CHANGE_CONFIRM_LOADING"
const DICT_TYPE_CHANGE_ADD_MODAL_VISIBLE = "DICT_TYPE_CHANGE_ADD_MODAL_VISIBLE"

export {
  DICT_TYPE_CHANGE_CONFIRM_LOADING,
  DICT_TYPE_QUERY_DICT_TYPE_LIST,
  DICT_TYPE_CHANGE_ADD_MODAL_VISIBLE,
  DICT_TYPE_CHANGE_SEARCH_PARAMS
}