const CLIENT_USER_QUERY_LIST = "CLIENT_USER_QUERY_LIST"
const CLIENT_USER_CHANGE_SEARCH_PARAMS = "CLIENT_USER_CHANGE_SEARCH_PARAMS"
const CLIENT_USER_CHANGE_MODAL_VISIBLE = "CLIENT_USER_CHANGE_MODAL_VISIBLE"
const CLIENT_USER_CHANGE_EDIT_STATUS = "CLIENT_USER_CHANGE_EDIT_STATUS"

export {
  CLIENT_USER_QUERY_LIST,
  CLIENT_USER_CHANGE_SEARCH_PARAMS,
  CLIENT_USER_CHANGE_MODAL_VISIBLE,
  CLIENT_USER_CHANGE_EDIT_STATUS,
}