const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_MODAL_VISIBLE = "CHANGE_MODAL_VISIBLE"
const CHANGE_EDIT_STATUS = "CHANGE_EDIT_STATUS"


export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_MODAL_VISIBLE,
  CHANGE_EDIT_STATUS,

}