const CHANGE_MENU_COLLAPSED = "CHANGE_MENU_COLLAPSED"
const USER_LOGOUT = 'USER_LOGOUT';
const INIT_ADMIN_INFO = 'INIT_ADMIN_INFO';

export {
  CHANGE_MENU_COLLAPSED,
  USER_LOGOUT,
  INIT_ADMIN_INFO
}