const BILLING_QUERY_LIST = "BILLING_QUERY_LIST"
const BILLING_CHANGE_SEARCH_PARAMS = "BILLING_CHANGE_SEARCH_PARAMS"
const BILLING_CHANGE_EDIT_TITLE = "BILLING_CHANGE_EDIT_TITLE"
const BILLING_CHANGE_EDIT_Amount = "BILLING_CHANGE_EDIT_Amount"
const BILLING_CHANGE_EDIT_TYPE = "BILLING_CHANGE_EDIT_TYPE"
const BILLING_CHANGE_SAVE_LOADING = "BILLING_CHANGE_SAVE_LOADING"
const BILLING_CHANGE_EDIT_MAX_LIMIT = "BILLING_CHANGE_EDIT_MAX_LIMIT"

export {
  BILLING_QUERY_LIST,
  BILLING_CHANGE_SEARCH_PARAMS,
  BILLING_CHANGE_EDIT_TITLE,
  BILLING_CHANGE_EDIT_Amount,
  BILLING_CHANGE_EDIT_TYPE,
  BILLING_CHANGE_SAVE_LOADING,
  BILLING_CHANGE_EDIT_MAX_LIMIT,
}