const QUERY_LIST = "QUERY_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_TITLE = "CHANGE_EDIT_TITLE"
const CHANGE_EDIT_Amount = "CHANGE_EDIT_Amount"
const CHANGE_EDIT_TYPE = "CHANGE_EDIT_TYPE"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"
const CHANGE_EDIT_MAX_LIMIT = "CHANGE_EDIT_MAX_LIMIT"

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_TITLE,
  CHANGE_EDIT_Amount,
  CHANGE_EDIT_TYPE,
  CHANGE_SAVE_LOADING,
  CHANGE_EDIT_MAX_LIMIT,
}