const LINK_QUERY_LIST = "LINK_QUERY_LIST"
const LINK_CHANGE_SEARCH_PARAMS = "LINK_CHANGE_SEARCH_PARAMS"
const LINK_CHANGE_EDIT_TITLE = "LINK_CHANGE_EDIT_TITLE"
const LINK_CHANGE_EDIT_URL = "LINK_CHANGE_EDIT_URL"
const LINK_CHANGE_EDIT_IMAGE_URL = "LINK_CHANGE_EDIT_IMAGE_URL"
const LINK_CHANGE_EDIT_STATUS = "LINK_CHANGE_EDIT_STATUS"

const LINK_CHANGE_SHOW_IMAGE = "LINK_CHANGE_SHOW_IMAGE"
const LINK_CHANGE_SAVE_LOADING = "LINK_CHANGE_SAVE_LOADING"

const LINK_CHANGE_EDIT_CONTENT = "LINK_CHANGE_EDIT_CONTENT"
const LINK_CHANGE_EDIT_REFTITLE = "LINK_CHANGE_EDIT_REFTITLE"
const LINK_INIT_NOTICE_DETAIL = "LINK_INIT_NOTICE_DETAIL"
const LINK_CHANGE_EDIT_STATE = "LINK_CHANGE_EDIT_STATE"


export {
  LINK_QUERY_LIST,
  LINK_CHANGE_SEARCH_PARAMS,
  LINK_CHANGE_EDIT_TITLE,
  LINK_CHANGE_EDIT_URL,
  LINK_CHANGE_EDIT_IMAGE_URL,
  LINK_CHANGE_EDIT_STATUS,
  LINK_CHANGE_SAVE_LOADING,
  LINK_CHANGE_SHOW_IMAGE,

  LINK_CHANGE_EDIT_CONTENT,
  LINK_CHANGE_EDIT_REFTITLE,
  LINK_INIT_NOTICE_DETAIL,
  LINK_CHANGE_EDIT_STATE,
}