const QUERY_LIST = "QUERY_LIST";
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS";
const SET_EDIT_ACCOUNT_NAME = "SET_EDIT_ACCOUNT_NAME";
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING";
const SET_EDIT_ACCOUNT_TYPE = "SET_EDIT_ACCOUNT_TYPE";
const SET_EDIT_ORG_CODE = "SET_EDIT_ORG_CODE";
const INIT_EDIT_ORG_LIST = "INIT_EDIT_ORG_LIST";
const SET_EDIT_PARENT_ACCOUNT = "SET_EDIT_PARENT_ACCOUNT";
const SET_EDIT_ACCESS_SCRECT = "SET_EDIT_ACCESS_SCRECT";
const SET_RE_CHARGE_TYPE = "SET_RE_CHARGE_TYPE";
const SET_RE_CHARGE_MONEY = "SET_RE_CHARGE_MONEY";
export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_SAVE_LOADING,
  SET_EDIT_ACCOUNT_NAME,
  SET_EDIT_ACCOUNT_TYPE,
  SET_EDIT_ORG_CODE,
  INIT_EDIT_ORG_LIST,
  SET_EDIT_PARENT_ACCOUNT,
  SET_EDIT_ACCESS_SCRECT,
  SET_RE_CHARGE_TYPE,
  SET_RE_CHARGE_MONEY
};
