const ACCOUNT_QUERY_LIST = "ACCOUNT_QUERY_LIST";
const ACCOUNT_CHANGE_SEARCH_PARAMS = "ACCOUNT_CHANGE_SEARCH_PARAMS";
const ACCOUNT_SET_EDIT_ACCOUNT_NAME = "ACCOUNT_SET_EDIT_ACCOUNT_NAME";
const ACCOUNT_CHANGE_SAVE_LOADING = "ACCOUNT_CHANGE_SAVE_LOADING";
const ACCOUNT_SET_EDIT_ACCOUNT_TYPE = "ACCOUNT_SET_EDIT_ACCOUNT_TYPE";
const ACCOUNT_SET_EDIT_ORG_CODE = "ACCOUNT_SET_EDIT_ORG_CODE";
const ACCOUNT_INIT_EDIT_ORG_LIST = "ACCOUNT_INIT_EDIT_ORG_LIST";
const ACCOUNT_SET_EDIT_PARENT_ACCOUNT = "ACCOUNT_SET_EDIT_PARENT_ACCOUNT";
const ACCOUNT_SET_EDIT_ACCESS_SCRECT = "ACCOUNT_SET_EDIT_ACCESS_SCRECT";
const ACCOUNT_SET_RE_CHARGE_TYPE = "ACCOUNT_SET_RE_CHARGE_TYPE";
const ACCOUNT_SET_RE_CHARGE_MONEY = "ACCOUNT_SET_RE_CHARGE_MONEY";
const ACCOUNT_QUERY_APP_LIST = "ACCOUNT_QUERY_APP_LIST";
const ACCOUNT_CHANGE_APP_SELECTED_KEYS = "ACCOUNT_CHANGE_APP_SELECTED_KEYS";
const ACCOUNT_INIT_RECHARGE_RULE_LIST = "ACCOUNT_INIT_RECHARGE_RULE_LIST";
const ACCOUNT_CHANGE_RECHARGE_RULE_LIST_LOADING = "ACCOUNT_CHANGE_RECHARGE_RULE_LIST_LOADING";


export {
  ACCOUNT_QUERY_LIST,
  ACCOUNT_CHANGE_SEARCH_PARAMS,
  ACCOUNT_CHANGE_SAVE_LOADING,
  ACCOUNT_SET_EDIT_ACCOUNT_NAME,
  ACCOUNT_SET_EDIT_ACCOUNT_TYPE,
  ACCOUNT_SET_EDIT_ORG_CODE,
  ACCOUNT_INIT_EDIT_ORG_LIST,
  ACCOUNT_SET_EDIT_PARENT_ACCOUNT,
  ACCOUNT_SET_EDIT_ACCESS_SCRECT,
  ACCOUNT_SET_RE_CHARGE_TYPE,
  ACCOUNT_SET_RE_CHARGE_MONEY,
  ACCOUNT_QUERY_APP_LIST,
  ACCOUNT_CHANGE_APP_SELECTED_KEYS,
  ACCOUNT_INIT_RECHARGE_RULE_LIST,
  ACCOUNT_CHANGE_RECHARGE_RULE_LIST_LOADING
};
