const ADMIN_QUERY_USER_LIST = "ADMIN_QUERY_USER_LIST"
const ADMIN_CHANGE_ADD_MODAL_VISIBLE = "ADMIN_CHANGE_ADD_MODAL_VISIBLE"
const ADMIN_CHANGE_SEARCH_PARAMS = "ADMIN_CHANGE_SEARCH_PARAMS"
const ADMIN_CHANGE_CONFIRM_LOADING = "ADMIN_CHANGE_CONFIRM_LOADING"
const ADMIN_INIT_SELECTED_ROLES = "ADMIN_INIT_SELECTED_ROLES"
const ADMIN_CHANGE_ROLE_MODAL_VISIBLE = "ADMIN_CHANGE_ROLE_MODAL_VISIBLE"
const ADMIN_INIT_ROLE_ALL_LIST = "ADMIN_INIT_ROLE_ALL_LIST"
const ADMIN_INIT_ROLE_ADMINID = "ADMIN_INIT_ROLE_ADMINID"
const ADMIN_CHANGE_CONFIRMLOADING_ROLE = "ADMIN_CHANGE_CONFIRMLOADING_ROLE"

export {
  ADMIN_QUERY_USER_LIST,
  ADMIN_CHANGE_ADD_MODAL_VISIBLE,
  ADMIN_CHANGE_SEARCH_PARAMS,
  ADMIN_CHANGE_CONFIRM_LOADING,
  ADMIN_INIT_SELECTED_ROLES,
  ADMIN_CHANGE_ROLE_MODAL_VISIBLE,
  ADMIN_INIT_ROLE_ALL_LIST,
  ADMIN_INIT_ROLE_ADMINID,
  ADMIN_CHANGE_CONFIRMLOADING_ROLE,
}