const QUERY_USER_LIST = "QUERY_USER_LIST"
const CHANGE_ADD_MODAL_VISIBLE = "CHANGE_ADD_MODAL_VISIBLE"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"
const INIT_SELECTED_ROLES = "INIT_SELECTED_ROLES"
const CHANGE_ROLE_MODAL_VISIBLE = "CHANGE_ROLE_MODAL_VISIBLE"
const INIT_ROLE_ALL_LIST = "INIT_ROLE_ALL_LIST"
const INIT_ROLE_ADMINID = "INIT_ROLE_ADMINID"
const CHANGE_CONFIRMLOADING_ROLE = "CHANGE_CONFIRMLOADING_ROLE"

export {
  QUERY_USER_LIST,
  CHANGE_ADD_MODAL_VISIBLE,
  CHANGE_SEARCH_PARAMS,
  CHANGE_CONFIRM_LOADING,
  INIT_SELECTED_ROLES,
  CHANGE_ROLE_MODAL_VISIBLE,
  INIT_ROLE_ALL_LIST,
  INIT_ROLE_ADMINID,
  CHANGE_CONFIRMLOADING_ROLE,
}