const QUERY_APP_LIST = "QUERY_APP_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_ROW_APP_ID = "CHANGE_ROW_APP_ID"

const CHANGE_FORM_APP_NAME = "CHANGE_FORM_APP_NAME"
const CHANGE_FORM_URL = "CHANGE_FORM_URL"
const CHANGE_FORM_DESCRIBES = "CHANGE_FORM_DESCRIBES"
const CHANGE_FORM_REDIRECTURL = "CHANGE_FORM_REDIRECTURL"
const CHANGE_FORM_ICON = "CHANGE_FORM_ICON"
const CHANGE_FORM_APPTYPE = "CHANGE_FORM_APPTYPE"
const CHANGE_FORM_AUDITMODE = "CHANGE_FORM_AUDITMODE"
const CHANGE_FORM_LANDINGMODES = "CHANGE_FORM_LANDINGMODES"
const CHANGE_FORM_SUPPORTCAS = "CHANGE_FORM_SUPPORTCAS"
const CHANGE_FORM_TAG = "CHANGE_FORM_TAG"
const INIT_ALL_LANDING_MODES = "INIT_ALL_LANDING_MODES"
const INIT_ALL_APP_TYPES = "INIT_ALL_APP_TYPES"
const INIT_ALL_SUPPORT_CAS = "INIT_ALL_SUPPORT_CAS"
const SET_ICON_BASE64 = "SET_ICON_BASE64"
const CHANGE_SAVE_LOADING = "CHANGE_SAVE_LOADING"
const CHANGE_FORM_EDIT_APP_ID = "CHANGE_FORM_EDIT_APP_ID"
const CHANGE_ROW_AUDIT_STATUS = "CHANGE_ROW_AUDIT_STATUS"
const EMPTY_ADD_VALUE = "EMPTY_ADD_VALUE"
const INIT_ORG_TREES = "INIT_ORG_TREES"
const CHANGE_TREE_ORG_CODE = "CHANGE_TREE_ORG_CODE"
const INIT_ALL_AUTH_LEVEL = "INIT_ALL_AUTH_LEVEL"
const INIT_CHARGE_DETAIL = "INIT_CHARGE_DETAIL"
const INIT_ALL_PRODUCT_TYPE = "INIT_ALL_PRODUCT_TYPE"
const CHANGE_PRODUCT = "CHANGE_PRODUCT"
const INIT_PRODUCT_LIST = "INIT_PRODUCT_LIST"
const INIT_BILLING_LIST = "INIT_BILLING_LIST"
const CHANGE_BILLING = "CHANGE_BILLING"
const CHANGE_BILLING_FETCHING = "CHANGE_BILLING_FETCHING"
const CHANGE_PREFERENTIAL_FETCHING = "CHANGE_PREFERENTIAL_FETCHING"
const INIT_PREFERENTIAL_LIST = "INIT_PREFERENTIAL_LIST"
const CHANGE_PREFERENTIAL = "CHANGE_PREFERENTIAL"

export {
  QUERY_APP_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_ROW_APP_ID,
  CHANGE_FORM_APP_NAME,
  CHANGE_FORM_URL,
  CHANGE_FORM_DESCRIBES,
  CHANGE_FORM_REDIRECTURL,
  CHANGE_FORM_ICON,
  CHANGE_FORM_APPTYPE,
  CHANGE_FORM_AUDITMODE,
  CHANGE_FORM_LANDINGMODES,
  CHANGE_FORM_SUPPORTCAS,
  CHANGE_FORM_TAG,
  INIT_ALL_LANDING_MODES,
  INIT_ALL_APP_TYPES,
  INIT_ALL_SUPPORT_CAS,
  SET_ICON_BASE64,
  CHANGE_SAVE_LOADING,
  CHANGE_FORM_EDIT_APP_ID,
  CHANGE_ROW_AUDIT_STATUS,
  EMPTY_ADD_VALUE,
  INIT_ORG_TREES,
  CHANGE_TREE_ORG_CODE,
  INIT_ALL_AUTH_LEVEL,
  INIT_CHARGE_DETAIL,
  INIT_ALL_PRODUCT_TYPE,
  CHANGE_PRODUCT,
  INIT_PRODUCT_LIST,
  INIT_BILLING_LIST,
  CHANGE_BILLING,
  CHANGE_BILLING_FETCHING,
  CHANGE_PREFERENTIAL_FETCHING,
  INIT_PREFERENTIAL_LIST,
  CHANGE_PREFERENTIAL
}