const APP_QUERY_APP_LIST = "APP_QUERY_APP_LIST"
const APP_CHANGE_SEARCH_PARAMS = "APP_CHANGE_SEARCH_PARAMS"
const APP_CHANGE_ROW_APP_ID = "APP_CHANGE_ROW_APP_ID"

const APP_CHANGE_FORM_APP_NAME = "APP_CHANGE_FORM_APP_NAME"
const APP_CHANGE_FORM_URL = "APP_CHANGE_FORM_URL"
const APP_CHANGE_FORM_DESCRIBES = "APP_CHANGE_FORM_DESCRIBES"
const APP_CHANGE_FORM_REDIRECTURL = "APP_CHANGE_FORM_REDIRECTURL"
const APP_CHANGE_FORM_ICON = "APP_CHANGE_FORM_ICON"
const APP_CHANGE_FORM_APPTYPE = "APP_CHANGE_FORM_APPTYPE"
const APP_CHANGE_FORM_AUDITMODE = "APP_CHANGE_FORM_AUDITMODE"
const APP_CHANGE_FORM_LANDINGMODES = "APP_CHANGE_FORM_LANDINGMODES"
const APP_CHANGE_FORM_SUPPORTCAS = "APP_CHANGE_FORM_SUPPORTCAS"
const APP_CHANGE_FORM_TAG = "APP_CHANGE_FORM_TAG"
const APP_INIT_ALL_LANDING_MODES = "APP_INIT_ALL_LANDING_MODES"
const APP_INIT_ALL_APP_TYPES = "APP_INIT_ALL_APP_TYPES"
const APP_INIT_ALL_SUPPORT_CAS = "APP_INIT_ALL_SUPPORT_CAS"
const APP_SET_ICON_BASE64 = "APP_SET_ICON_BASE64"
const APP_CHANGE_SAVE_LOADING = "APP_CHANGE_SAVE_LOADING"
const APP_CHANGE_FORM_EDIT_APP_ID = "APP_CHANGE_FORM_EDIT_APP_ID"
const APP_CHANGE_ROW_AUDIT_STATUS = "APP_CHANGE_ROW_AUDIT_STATUS"
const APP_EMPTY_ADD_VALUE = "APP_EMPTY_ADD_VALUE"
const APP_INIT_ORG_TREES = "APP_INIT_ORG_TREES"
const APP_CHANGE_TREE_ORG_CODE = "APP_CHANGE_TREE_ORG_CODE"
const APP_INIT_ALL_AUTH_LEVEL = "APP_INIT_ALL_AUTH_LEVEL"
const APP_INIT_ALL_PRODUCT_TYPE = "APP_INIT_ALL_PRODUCT_TYPE"
const APP_CHANGE_PRODUCT = "APP_CHANGE_PRODUCT"
const APP_INIT_PRODUCT_LIST = "APP_INIT_PRODUCT_LIST"
const APP_INIT_BILLING_LIST = "APP_INIT_BILLING_LIST"
const APP_CHANGE_BILLING = "APP_CHANGE_BILLING"
const APP_CHANGE_BILLING_FETCHING = "APP_CHANGE_BILLING_FETCHING"
const APP_CHANGE_PREFERENTIAL_FETCHING = "APP_CHANGE_PREFERENTIAL_FETCHING"
const APP_INIT_PREFERENTIAL_LIST = "APP_INIT_PREFERENTIAL_LIST"
const APP_CHANGE_PREFERENTIAL = "APP_CHANGE_PREFERENTIAL"

export {
  APP_QUERY_APP_LIST,
  APP_CHANGE_SEARCH_PARAMS,
  APP_CHANGE_ROW_APP_ID,
  APP_CHANGE_FORM_APP_NAME,
  APP_CHANGE_FORM_URL,
  APP_CHANGE_FORM_DESCRIBES,
  APP_CHANGE_FORM_REDIRECTURL,
  APP_CHANGE_FORM_ICON,
  APP_CHANGE_FORM_APPTYPE,
  APP_CHANGE_FORM_AUDITMODE,
  APP_CHANGE_FORM_LANDINGMODES,
  APP_CHANGE_FORM_SUPPORTCAS,
  APP_CHANGE_FORM_TAG,
  APP_INIT_ALL_LANDING_MODES,
  APP_INIT_ALL_APP_TYPES,
  APP_INIT_ALL_SUPPORT_CAS,
  APP_SET_ICON_BASE64,
  APP_CHANGE_SAVE_LOADING,
  APP_CHANGE_FORM_EDIT_APP_ID,
  APP_CHANGE_ROW_AUDIT_STATUS,
  APP_EMPTY_ADD_VALUE,
  APP_INIT_ORG_TREES,
  APP_CHANGE_TREE_ORG_CODE,
  APP_INIT_ALL_AUTH_LEVEL,
  APP_INIT_ALL_PRODUCT_TYPE,
  APP_CHANGE_PRODUCT,
  APP_INIT_PRODUCT_LIST,
  APP_INIT_BILLING_LIST,
  APP_CHANGE_BILLING,
  APP_CHANGE_BILLING_FETCHING,
  APP_CHANGE_PREFERENTIAL_FETCHING,
  APP_INIT_PREFERENTIAL_LIST,
  APP_CHANGE_PREFERENTIAL
}