const INIT_LIST = "INIT_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_SETTING_EXP = "CHANGE_EDIT_SETTING_EXP"
const CHANGE_EDIT_SETTING_KEY = "CHANGE_EDIT_SETTING_KEY"
const CHANGE_EDIT_SETTING_VALUE = "CHANGE_EDIT_SETTING_VALUE"

export {
  INIT_LIST,
  CHANGE_EDIT_SETTING_EXP,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_SETTING_KEY,
  CHANGE_EDIT_SETTING_VALUE
}