const PLAT_SETTING_INIT_LIST = "PLAT_SETTING_INIT_LIST"
const PLAT_SETTING_CHANGE_SEARCH_PARAMS = "PLAT_SETTING_CHANGE_SEARCH_PARAMS"
const PLAT_SETTING_CHANGE_EDIT_SETTING_EXP = "PLAT_SETTING_CHANGE_EDIT_SETTING_EXP"
const PLAT_SETTING_CHANGE_EDIT_SETTING_KEY = "PLAT_SETTING_CHANGE_EDIT_SETTING_KEY"
const PLAT_SETTING_CHANGE_EDIT_SETTING_VALUE = "PLAT_SETTING_CHANGE_EDIT_SETTING_VALUE"

export {
  PLAT_SETTING_INIT_LIST,
  PLAT_SETTING_CHANGE_EDIT_SETTING_EXP,
  PLAT_SETTING_CHANGE_SEARCH_PARAMS,
  PLAT_SETTING_CHANGE_EDIT_SETTING_KEY,
  PLAT_SETTING_CHANGE_EDIT_SETTING_VALUE
}