const OAPI_QUERY_LIST = "OAPI_QUERY_LIST";
const OAPI_CHANGE_SEARCH_PARAMS = "OAPI_CHANGE_SEARCH_PARAMS";
const OAPI_SET_API_NAME = "OAPI_SET_API_NAME";
const OAPI_INIT_TYPE_LIST = "OAPI_INIT_TYPE_LIST";
const OAPI_SET_TYPE_ID = "OAPI_SET_TYPE_ID";
const OAPI_SET_API_REQ_TYPE = "OAPI_SET_API_REQ_TYPE";
const OAPI_SET_API_URL = "OAPI_SET_API_URL";
const OAPI_SET_API_PARAM_TYPE = "OAPI_SET_API_PARAM_TYPE";
const OAPI_SET_API_REMARKS = "OAPI_SET_API_REMARKS";
const OAPI_SET_API_PARAMS_DETAIL = "OAPI_SET_API_PARAMS_DETAIL";

export {
  OAPI_QUERY_LIST,
  OAPI_CHANGE_SEARCH_PARAMS,
  OAPI_SET_API_NAME,
  OAPI_INIT_TYPE_LIST,
  OAPI_SET_TYPE_ID,
  OAPI_SET_API_REQ_TYPE,
  OAPI_SET_API_URL,
  OAPI_SET_API_PARAM_TYPE,
  OAPI_SET_API_REMARKS,
  OAPI_SET_API_PARAMS_DETAIL
};
