const QUERY_LIST = "QUERY_LIST";
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS";
const SET_API_NAME = "SET_API_NAME";
const INIT_TYPE_LIST = "INIT_TYPE_LIST";
const SET_TYPE_ID = "SET_TYPE_ID";
const SET_API_REQ_TYPE = "SET_API_REQ_TYPE";
const SET_API_URL = "SET_API_URL";
const SET_API_PARAM_TYPE = "SET_API_PARAM_TYPE";
const SET_API_REMARKS = "SET_API_REMARKS";

export {
  QUERY_LIST,
  CHANGE_SEARCH_PARAMS,
  SET_API_NAME,
  INIT_TYPE_LIST,
  SET_TYPE_ID,
  SET_API_REQ_TYPE,
  SET_API_URL,
  SET_API_PARAM_TYPE,
  SET_API_REMARKS
};
