const INIT_LIST = "INIT_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_AUTH_NAME = "CHANGE_EDIT_AUTH_NAME"
const CHANGE_EDIT_URL = "CHANGE_EDIT_URL"
const CHANGE_AUTH_LEVE = "CHANGE_AUTH_LEVE"
const CHANGE_AUTH_STYLE = "CHANGE_AUTH_STYLE"
const CHANGE_EDIT_STATUS = "CHANGE_EDIT_STATUS"
const CLEAN_FORM = "CLEAN_FORM"


const CHANGE_EDIT_CONTENT = "CHANGE_EDIT_CONTENT"
const CHANGE_EDIT_REFTITLE = "CHANGE_EDIT_REFTITLE"
const INIT_NOTICE_DETAIL = "INIT_NOTICE_DETAIL"



export {
  INIT_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_AUTH_NAME,
  CHANGE_EDIT_URL,
  CHANGE_AUTH_LEVE,
  CHANGE_AUTH_STYLE,
  CHANGE_EDIT_STATUS,
  CLEAN_FORM,

  CHANGE_EDIT_CONTENT,
  CHANGE_EDIT_REFTITLE,
  INIT_NOTICE_DETAIL,
}