const INIT_LIST = "INIT_LIST"
const INIT_PRODUCT_LIST = "INIT_PRODUCT_LIST"
const CHANGE_SEARCH_PARAMS = "CHANGE_SEARCH_PARAMS"
const CHANGE_EDIT_PRODUCT_CODE = "CHANGE_EDIT_PRODUCT_CODE"
const CHANGE_EDIT_NAME = "CHANGE_EDIT_NAME"
const CHANGE_EDIT_ORDERS = "CHANGE_EDIT_ORDERS"


export {
  INIT_LIST,
  INIT_PRODUCT_LIST,
  CHANGE_SEARCH_PARAMS,
  CHANGE_EDIT_PRODUCT_CODE,
  CHANGE_EDIT_NAME,
  CHANGE_EDIT_ORDERS,
}