const DOC_CATALOG_INIT_LIST = "DOC_CATALOG_INIT_LIST"
const DOC_CATALOG_INIT_PRODUCT_LIST = "DOC_CATALOG_INIT_PRODUCT_LIST"
const DOC_CATALOG_CHANGE_SEARCH_PARAMS = "DOC_CATALOG_CHANGE_SEARCH_PARAMS"
const DOC_CATALOG_CHANGE_EDIT_PRODUCT_CODE = "DOC_CATALOG_CHANGE_EDIT_PRODUCT_CODE"
const DOC_CATALOG_CHANGE_EDIT_NAME = "DOC_CATALOG_CHANGE_EDIT_NAME"
const DOC_CATALOG_CHANGE_EDIT_ORDERS = "DOC_CATALOG_CHANGE_EDIT_ORDERS"

export {
  DOC_CATALOG_INIT_LIST,
  DOC_CATALOG_INIT_PRODUCT_LIST,
  DOC_CATALOG_CHANGE_SEARCH_PARAMS,
  DOC_CATALOG_CHANGE_EDIT_PRODUCT_CODE,
  DOC_CATALOG_CHANGE_EDIT_NAME,
  DOC_CATALOG_CHANGE_EDIT_ORDERS,
}