const OAPI_TYPES_QUERY_LIST = "OAPI_TYPES_QUERY_LIST";
const OAPI_TYPES_CHANGE_MODAL_VISIBLE = "OAPI_TYPES_CHANGE_MODAL_VISIBLE";
const OAPI_TYPES_SAVE_LOADING = "OAPI_TYPES_SAVE_LOADING";
const OAPI_TYPES_CHANGE_TYPE_NAME = "OAPI_TYPES_CHANGE_TYPE_NAME";
const OAPI_TYPES_CHANGE_TYPE_REMARKS = "OAPI_TYPES_CHANGE_TYPE_REMARKS";
const OAPI_TYPES_CHANGE_STRATEGY_STATUS = "OAPI_TYPES_CHANGE_STRATEGY_STATUS";
const OAPI_TYPES_CHANGE_CONFIRM_LOADING = "OAPI_TYPES_CHANGE_CONFIRM_LOADING";

export {
  OAPI_TYPES_QUERY_LIST,
  OAPI_TYPES_CHANGE_MODAL_VISIBLE,
  OAPI_TYPES_SAVE_LOADING,
  OAPI_TYPES_CHANGE_TYPE_NAME,
  OAPI_TYPES_CHANGE_TYPE_REMARKS,
  OAPI_TYPES_CHANGE_STRATEGY_STATUS,
  OAPI_TYPES_CHANGE_CONFIRM_LOADING
};
