const QUERY_LIST = "QUERY_LIST"
const CHANGE_MODAL_VISIBLE = "CHANGE_MODAL_VISIBLE"
const SAVE_LOADING = "SAVE_LOADING"
const CHANGE_TYPE_NAME = "CHANGE_TYPE_NAME"
const CHANGE_TYPE_REMARKS = "CHANGE_TYPE_REMARKS"
const CHANGE_STRATEGY_STATUS = "CHANGE_STRATEGY_STATUS"
const CHANGE_CONFIRM_LOADING = "CHANGE_CONFIRM_LOADING"

export {
  QUERY_LIST,
  CHANGE_MODAL_VISIBLE,
  SAVE_LOADING,
  CHANGE_TYPE_NAME,
  CHANGE_TYPE_REMARKS,
  CHANGE_STRATEGY_STATUS,
  CHANGE_CONFIRM_LOADING
}