const CHARGE_CONSUME_QUERY_LIST = "CHARGE_CONSUME_QUERY_LIST";
const CHARGE_CONSUME_CHANGE_SEARCH_PARAMS = "CHARGE_CONSUME_CHANGE_SEARCH_PARAMS";
const CHARGE_CONSUME_INIT_DETAIL = "CHARGE_CONSUME_INIT_DETAIL";

export { CHARGE_CONSUME_QUERY_LIST, CHARGE_CONSUME_CHANGE_SEARCH_PARAMS, CHARGE_CONSUME_INIT_DETAIL };
